### ISSUE TITLE
Unusual crash on Spark + MKL + Linux

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1460] opened 2016-11-26 10:36 UTC
I'm using MKL binaries as discussed previously.

However, now when running Spark I'm hitting this:
This occurs locally and on a customer cluster.
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000003120609d0f, pid=21888, tid=0x00007f0fcb9a1700
#
# JRE version: OpenJDK Runtime Environment (8.0_111-b15) (build 1.8.0_111-b15)
# Java VM: OpenJDK 64-Bit Server VM (25.111-b15 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [ld-linux-x86-64.so.2+0x9d0f]
#
# Core dump written. Default location: /mnt/disk2/hadoop/yarn/local/usercache/platform/appcache/application_1447179492962_20894/container_1447179492962_20894_01_000007/core or core.21888
#
# An error report file with more information is saved as:
# /mnt/disk2/hadoop/yarn/local/usercache/platform/appcache/application_1447179492962_20894/container_1447179492962_20894_01_000007/hs_err_pid21888.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

Run locally (MLP MNIST Spark example) after adding the MKL binaries from our repo:
https://gist.github.com/AlexDBlack/90c8f09e84f845cccdb61bf8948e67d6

Note that the crash isn't happening immediately when run locally - but rather, after some time.

**Comment by saudet** [comment] 2016-11-26 10:49
Did it used to work with MKL though with 0.6.0?

**Comment by AlexDBlack** [comment] 2016-11-26 11:06
Good question. I'll have to test that - previously I've only ever used MKL with Windows.

**Comment by AlexDBlack** [comment] 2016-11-26 11:34
Running locally with 0.6.0 (dl4j examples as of 1316b5a0abfccea84c180ceec493d45d421158bd - i.e., "get rid of nd4j.dtype") + the MKL binaries - it runs without issue. I'm running via mvn package + java -cp (see gist)

I'm pretty sure (but not 100% - what's the best way to verify?) that it's linking with MKL. The MKL binaries are certainly on the classpath.

So at this point: either they are not being linked correctly with 0.6.0 for some reason, or it's specific to 0.7.0 + MKL.

https://gist.github.com/AlexDBlack/2069f96e418f6b212e0f674880f6b5e9

**Comment by AlexDBlack** [comment] 2016-11-26 12:43
Also: I've run a number of non-Spark examples (lenet, MLPMnistTwoLayer, character example) with these MKL binaries without issue.

**Comment by AlexDBlack** [comment] 2016-11-26 13:10
Another update: This does not seem to occur if I build from source + add the MKL binaries.
(Specifically, I was going to test branch r119_gemm_fallback, but I can't reproduce it on that branch before enabling the fallback). I will retest master tomorrow.

Something else I'll check tomorrow: a standard MKL install and linking via path for 0.7.0.

**Comment by saudet** [comment] 2016-11-27 03:07
`MnistMLPExample` works fine for me with MKL either in `LD_LIBRARY_PATH` or bundled in an user JAR, but the version of MKL that is currently in the `nd4j-mkl` artifact does not work for me. The version that works for me is:
```
Intel(R) Math Kernel Library Version 11.3.3 Product Build 20160413 for Intel(R) 64 architecture applications
```
as returned by
```c
int main(void) {
  char buf[198];
  mkl_get_version_string(buf, 198);
  printf("%s\n",buf);
}
```
But the version currently in `nd4j-mkl` returns this:
```
Intel(R) Math Kernel Library Version 2017.0.0 Product Build 20160801 for Intel(R) 64 architecture applications
```
So, something fundamental changed in that version there it seems.

**Comment by saudet** [comment] 2016-11-27 03:21
Actually, either versions seem to be fine when loaded externally with `LD_LIBRARY_PATH`. I'll have to look into that...

**Comment by AlexDBlack** [comment] 2016-11-27 03:56
One thing I tried: deleting libiomp5.so from the nd4j mkl binaries (after comparing the nd4j-mkl contents to the jar that actually gets built on an install)
It seems to work without issue after doing that. That might explain why we're seeing failures in code other than those libraries we are adding...

This can be closed perhaps?

**Comment by saudet** [comment] 2016-11-27 09:44
Looks like the issue was caused by JavaCPP loading `libmkl_rt.so` as `libopenblas.so.0`, but then overwriting `libopenblas.so.0` with OpenBLAS itself, and reloading that. That most certainly causes the kind of crash we were seeing with Linux's loader. With the fix above, everything seems fine on my end with whatever version of OpenMP, at least for uber JARs. MKL has a really weird way of loading its libraries, and to make them behave better for non-uber JARs, we might have to hack them with [patchelf](http://nixos.org/patchelf.html) or something.

**Comment by huitseeker** [comment] 2017-06-06 18:57
@saudet Congrats on the sleuth work ! Should we close this issue, then, or reopen a more specific one ?

**Comment by saudet** [comment] 2017-06-07 01:46
I think we can close this for now, yes, it should work fine. We can always reopen if it comes back to bite.

**Closed** 2017-06-07 16:15 UTC
Labels: bug
