### ISSUE TITLE
CUDA state & plans

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#919] opened 2016-05-09 20:14 UTC
Current CUDA bottlenecks, bugs, plans etc:

- Async flow controller isn't working properly, and should be thoroughly investigated.
- TADs should be cached and reused, instead of calculating them in runtime. Probably worth adding TAD shape as argument to all corresponding methods, and manage cache from java side.
- @AlexDBlack investigates optimal C/F order for mmul, but that's actually worth doing for all operations where it's possible to get to stride == 1
- Registers use still a concern. Probably after we have tad removed it'll be better, but no guarantees there yet. So it looks that we'll have to split all kernels in to atomic kernels, without code branches. Also, registers use within shape.h should be thoroughly checked.
- For LSTM impl main time consumers are pairwiseStridedT, broadcastT and reduceT calls.

**Comment by raver119** [comment] 2016-05-10 09:47
Also, hybrid execution is still a concern.

**Comment by AlexDBlack** [comment] 2016-05-10 09:57
I can confirm currently that we will be hitting some of the 'bad' mmuls (i.e., poor cuda mmul performance due to input array orders being poorly matched) in RNNs (notably ff->f mmuls). Not sure on MLPs; working on CNNs now with this in mind.

**Comment by raver119** [comment] 2016-05-10 09:58
@AlexDBlack Don't forget about reductions too, we've discussed that yesterday. More calls with stride == 1 we have - the better performance we get.

**Comment by saudet** [comment] 2016-05-10 10:03
@raver119 When you say "hybrid" are you talking about using both `nd4j-native` and `nd4j-cuda-7.5` backends together?

**Comment by raver119** [comment] 2016-05-10 10:23
Exactly. Even the most cool GPU has it's execution limits. And this means that on AWS you'll have plenty of CPU power which isn't used.

**Comment by raver119** [comment] 2016-05-10 16:16
So far: @AlexDBlack confirmed passed gradient checks, however MLP example gives different results somehow.

Initial suspect for that behavior was declined, so issue is to be investigated.

**Comment by raver119** [comment] 2016-05-10 22:36
So yea, to go below 1.9s shared memory and register use should be greatly decreased. Getting rid of TAD inside kernels will work fine for that. It'll reduce amount of required shared memory by ~216 bytes in case without device constant memory, and ~344 bytes in case of device constant memory use.

**Comment by raver119** [comment] 2016-05-11 10:19
Minor fix needed: We create short-living buffers for dimensional data in operations. That has to be reconsidered.

**Comment by raver119** [comment] 2016-05-11 13:19
Even with all tests passing, IMax is wrong with F order. Need to be fixed asap.

**Comment by raver119** [comment] 2016-05-12 16:45
Current profiler view:

![05122016](https://cloud.githubusercontent.com/assets/12250879/15222827/1ef31540-187a-11e6-9df9-91862fa921f3.png)

**Comment by AlexDBlack** [comment] 2016-05-13 00:11
@raver119 "For LSTM impl main time consumers are pairwiseStridedT, broadcastT and reduceT calls."
I think the pairwise stuff could be .dup('f')s from an existing f order; also some mulis, which should also be f .x f I think
broadcast is addiRowVector and muliRowVector on f order arrays, so in theory this should be fast here, if each thread operates on one column, and slow if it operates on the rows due to strides (reverse performance tradeoff for c order)
Reduce calls should all be sum(0) ops on f order arrays

**Comment by raver119** [comment] 2016-05-13 10:01
no, dup('f') from existing f ordered array will be simple memcpy in D2D mode. That improvement was introduced few weeks ago.

Right now main issue here is shared memory and reigsters use within kernerls.

**Comment by raver119** [comment] 2016-05-13 10:51
So, i've split reduce kernel into multiple "specialized" kernels. And memory consumption stays the same:

reduceFloat regs: [54], static shmem: [896]
reduceFloat1D regs: [54], static shmem: [896]
reduceFloat6D regs: [54], static shmem: [896]

**Comment by raver119** [comment] 2016-05-13 11:18
So, here's current PTXAS output: https://gist.github.com/raver119/f05d8091afd41fa694f6bc71c989d7cb

Please note, 16 regs max was forced by me, and it's NOT a solution.

**Comment by raver119** [comment] 2016-05-13 11:30
And here's "unbounded" PTXAS output, without forced registers limit: https://gist.github.com/raver119/e164bcf6a5a271ea654dc5936dd255a9

**Comment by raver119** [comment] 2016-05-13 12:00
And here's the lastest profiler report:

![05122016](https://cloud.githubusercontent.com/assets/12250879/15247223/611dc2a2-191b-11e6-9128-ed9510fa153b.png)

**Comment by raver119** [comment] 2016-05-13 12:01
@AlexDBlack so, according to latest profiler report: all reductions are along 1 dimension.

**Comment by eraly** [comment] 2016-05-13 18:58
Only the functions with spill, sorted by spill loads
https://gist.github.com/eraly/e8a79444f838190d622c7d5a4c1cbef1

**Comment by raver119** [comment] 2016-05-13 20:58
Since it's 2 days till release, this issue won't be considered closed even after latest changes pack merged, and will be carried over to next release.

So, current issues: 
- non-optimal code being generated for TAD class on gpu. That causes high registers use. I think that's mostly due to tad2sub. But further investigation required. 
- Launch params do no take registers used into account. Fast fix though.
- Async executor is disabled by default. Sequential execution used instead.
- Static shared memory footprint is still under investigation.


To be continued...

**Comment by raver119** [comment] 2016-05-14 19:06
So, with full-cached TAD prototype on reduce only benchmarked RNN shows 1150 ms per iteration.

Major bottleneck now is 896 bytes of shared memory that's requested by compiler for yet unknown reason. I think it's time to look into PTX code.

**Comment by AlexDBlack** [comment] 2016-05-15 02:35
Results from running examples (nd4j/libnd4j master)

*** FeedForward Examples ***
- MNISTAnomalyExample: OK (scores and images)
- MLPClassifierLinear: OK
- MLPClassifierMoon: OK (scores, accuracy, plots)
- MLPClassifierSaturn: OK (scores, accuracy, plots)
- MLPMnistSingleLayerExample: OK (scores, accuracy)
- MLPMnistTwoLayerExample: 
- RegressionMathFunctions: 

*** RNN Examples ***
- GravesLSTMCharModellingExample (40 minibatches): 	**Significantly different scores** but both seem to learn and give sensible results when sampling
- Word2VecSentimentRNN: "java.lang.RuntimeException: Can't allocate [HOST] memory: 3600000000". These are the word vectors, obviously (3 million words x 300 floats = 900m floats ~= 3600mb). xms/xmx 16G doesn't help
- VideoClassificationExample - broken on nd4j-native too (mismatched shapes exception in sequence record reader)

*** CNN Example ***
- LenetMnistExample: **exception** https://gist.github.com/AlexDBlack/9ce651e8f1162fb063aa4feb36694513

**Comment by AlexDBlack** [comment] 2016-05-15 04:27
**Gradient checks on CUDA**
GradientCheckTests: 11 of 14 passing. Tests failing:
- testGradientGravesLSTMEdgeCases and testGradientGravesBidirectionalLSTMEdgeCases: exception in GemmParams (also: nd4j-native)
- testGradientCnnFfRnn: gradient check failure

CNNGradientCheckTests: all failing, including on @eraly's eraly_cuda branch

GradientCheckTestsComputationGraph: all passing

GradientCheckTestsMasking: exception in GemmParams (also: nd4j-native)

**Comment by raver119** [comment] 2016-05-15 13:15
Among other planned fixes & improvements: reconsider summaryStats kernel, to make it work with default stack settings. Right now it's too hungry due to struct it uses internally.

**Comment by raver119** [comment] 2016-05-16 09:37
Despite concat is blockwise now, it should be rewritten. It's not a proper kernel in any sense.

**Comment by agibsonccc** [comment] 2016-05-22 13:46
I'm closing this. We released rc3.9 a bit ago.

**Closed by agibsonccc** 2016-05-22 13:46 UTC
Labels: enhancement, perf
