### ISSUE TITLE
Invoking DataTypeUtil.setDTypeForContext(DataBuffer.Type) twice messes with duplicating the existing NDArray instances

### ISSUE THREAD

**Issue by mbabadi** [deeplearning4j/nd4j#1041] opened 2016-06-22 23:02 UTC
I get this behavior with 0.4-rc3.10:macosx-x86_64 from Maven. Here's a test:

    public void testNd4jDup() {
        /* set the dType */
        DataTypeUtil.setDTypeForContext(DataBuffer.Type.DOUBLE);

        /* create NDArray from a double[][] */
        double data[][] = new double[50][50];
        IntStream.range(0, 50).forEach(s -> data[s] = IntStream.range(0, 50).mapToDouble(n -> 100.0).toArray());
        INDArray testNDArray = Nd4j.create(data);

        /* print the first row */
        System.out.println(testNDArray.getRow(0));

        /* set the dType again! */
        DataTypeUtil.setDTypeForContext(DataBuffer.Type.DOUBLE);

        /* print the first row */
        System.out.println(testNDArray.getRow(0));

        /* print the first row dup -- it should be different now! */
        System.out.println(testNDArray.getRow(0).dup());
    }

**Comment by mbabadi** [comment] 2016-06-22 23:05
Processor: 2.8 GHz Intel Core i7
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

**Comment by treo** [comment] 2016-06-23 07:45
The problem is that when you create `testNDArray`, Nd4j is initialized, that means that your setting is overwritten. For that reason the docs used to contain an `Nd4j.create(1)` before setting the data type.

@AlexDBlack any reason why that was removed?

Anyway, the behavior you are seeing stems from creating a float based NDArray, and then setting the datatype to double. As internally everything works on pointers, this makes dup reinterpret the float as a double, and thus the you are seeing that garbage values.

**Comment by raver119** [comment] 2016-06-23 07:47
But it his example, both datatypes are DOUBLE. So i'm kinda surprised.

If that's a typo, and first setDType() is for FLOAT,  then it's "working as intended" and user's mistake.

**Comment by raver119** [comment] 2016-06-23 07:51
And no, that's not a typo. Issue is reproducible for me.

**Comment by treo** [comment] 2016-06-23 07:51
No, even in his example the DataType at the time of array creation is FLOAT.

**Comment by raver119** [comment] 2016-06-23 07:53
Aha, so first setDType call is ignored...

**Comment by raver119** [comment] 2016-06-23 07:53
I'll just wrape Nd4j.create(1) right there, in setDType call.

**Comment by treo** [comment] 2016-06-23 07:54
It isn't ignored, but it is overwritten.

```
Datatype After Setting it first:double
o.n.n.NativeOps - Number of threads used for linear algebra 1
o.n.n.NativeOps - Number of threads used for linear algebra 1
Datatype After Array creation:float
[100,00,...]
Datatype After Setting it second:double
[100,00,..]
[52.776.566.886.400,00,..]
```

**Comment by raver119** [comment] 2016-06-23 08:15
Fixed here: https://github.com/deeplearning4j/nd4j/pull/1025

Will be merged a bit later, as usually.

Thanks for highlighting this issue.

**Closed by raver119** 2016-06-23 08:15 UTC
Labels: bug

**Comment by mbabadi** [comment] 2016-06-27 17:53
Thanks @raver119 for fixing this!
