### ISSUE TITLE
PairwiseTransofrms bug

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#1562] opened 2017-01-02 11:33 UTC
There's a bug in PairwiseTransforms that leaked through tests: In case of mixed order inputs/output order is considered C always.

Fix will be available asap.

**Comment by raver119** [comment] 2017-01-03 09:29
After discussion with @AlexDBlack we definitely can say that it's not a bug, but convention.

**Comment by chenhuang-learn** [comment] 2017-01-04 02:53
why it's not a bug? i can't understand, can i see the discussion?

here is my test code, it's very strange.
```
public static INDArray create(int m, int n, char order){
        INDArray data = Nd4j.create(m, n, order);
        for (int i = 0; i < m; ++i){
            for (int j = 0; j < n; ++j){
                data.put(i, j, Math.random());
            }
        }
        return data;
    }

    public static void testPairWiseTransform() {
        int m=2, n=3;
        INDArray af = create(m, n, 'f');
        INDArray bf = create(m, n, 'f');
        INDArray cf = create(m, n, 'f');
        INDArray cc = create(m, n, 'c');

        System.out.println(af);
        System.out.println(bf);

        af.addi(bf, cf);
        System.out.println("fff:" +  cf);
        System.out.println(cf.ordering());
        af.addi(bf, cc);
        System.out.println("ffc:" +  cc);
        System.out.println(cc.ordering());
    }
```

**Comment by raver119** [comment] 2017-01-04 08:33
Sure. To tackle issue, i've added multiple tests, that involve operations on different orders. Here they are:

https://github.com/deeplearning4j/nd4j/blob/53e4893fc66768c959415bca3b7e3b43564c207a/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/Nd4jTestsC.java#L3113-L3235

**Comment by chenhuang-learn** [comment] 2017-01-04 12:04
@raver119  can you test my code?

this bug happens only when use the above method (i showed) to initialize arrays .

**Comment by agibsonccc** [comment] 2017-01-27 03:53
@chenhuang-learn if it's working on master there's nothing more we can do. Closing this.

**Closed by agibsonccc** 2017-01-27 03:53 UTC
Labels: bug
