### ISSUE TITLE
CUDA segmentation fault while allocating large array

### ISSUE THREAD

**Issue by akhodakivskiy** [deeplearning4j/nd4j#1115] opened 2016-07-14 20:54 UTC
Running the following program against `0.4.0` with `nd4j-cuda-7.5` backend results in segmentation fault. I'm running this against GTX 980 4Gb. This used to work with previous RC version.

Scala: https://gist.github.com/akhodakivskiy/5273439c13134baf4dd172793798084d
Java: https://gist.github.com/akhodakivskiy/556fbd19440c549aee663412d7712262

Here is the dump from the Java process:

https://gist.github.com/akhodakivskiy/34de771a73879649d0e1574326f9639a

**Comment by raver119** [comment] 2016-07-14 21:20
Could you please translate sample into Java, since i'm not scala programmer i'm afraid that my translation might be wrong.

**Comment by raver119** [comment] 2016-07-14 21:24
It's 200k x 500 as feature array, and 200k x 2  as labels array, right?

**Comment by raver119** [comment] 2016-07-14 21:45
Thanks, i'll take care of it.

**Comment by akhodakivskiy** [comment] 2016-07-14 21:45
I just updated the main text with a link to a Java program - subject to compilation errors :)

But yes, essentially initializing 200k x 500 INDArray on CUDA seems to fail

**Comment by raver119** [comment] 2016-07-15 18:39
Issue is reproducible, but only for larger X values, like 400k x 500.

Thanks for flagging this.

**Comment by raver119** [comment] 2016-07-15 19:40
Fixed here: https://github.com/deeplearning4j/nd4j/pull/1112

However, will be merged a bit later.

**Closed by raver119** 2016-07-15 19:40 UTC
Labels: bug
