### ISSUE TITLE
Exception when loading a saved INDArray with integers on CUDA backend

### ISSUE THREAD

**Issue by EdeMeijer** [deeplearning4j/nd4j#1453] opened 2016-11-21 15:09 UTC
Not sure what's going on, but as far as I know creating a buffer with integer values should work fine on all backends. The following code works fine on the native backend, but fails with the CUDA backend.

```
 // Create temp file
File tempFile = File.createTempFile("test", "test");
tempFile.deleteOnExit();

// Save some ints into it
Nd4j.saveBinary(Nd4j.create(Nd4j.createBuffer(new int[]{1, 2, 3})), tempFile);

// Load it again
InputStream stream = new FileInputStream(tempFile);
BufferedInputStream bis = new BufferedInputStream(stream);
DataInputStream dis = new DataInputStream(bis);

INDArray loaded = Nd4j.read(dis);

// Read one of the ints
System.out.println(loaded.getInt(1));
```

When running this with the CUDA 8.0 backend, I get this exception:
```
Exception in thread "main" java.lang.ClassCastException: org.bytedeco.javacpp.indexer.IntRawIndexer cannot be cast to org.bytedeco.javacpp.indexer.UByteRawIndexer
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.getFloat(BaseDataBuffer.java:854)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.getFloat(BaseCudaDataBuffer.java:919)
	at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.getDouble(CudaFloatDataBuffer.java:225)
	at org.nd4j.linalg.api.shape.Shape.getDouble(Shape.java:168)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:1545)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getInt(BaseNDArray.java:1525)
	at io.buybrain.brain.AppPrepareRNN4Data.main(AppPrepareRNN4Data.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Process finished with exit code 1
```

When changing 
```
Nd4j.saveBinary(Nd4j.create(Nd4j.createBuffer(new int[]{1, 2, 3})), tempFile);
```
to
```
Nd4j.saveBinary(Nd4j.create(Nd4j.createBuffer(new float[]{1, 2, 3})), tempFile);
```
it works fine.

**Comment by EdeMeijer** [comment] 2016-11-21 15:09
This is on the master branch btw

**Comment by raver119** [comment] 2016-11-21 15:11
Stick to proper write method: Nd4j.write();

**Comment by EdeMeijer** [comment] 2016-11-21 15:14
`saveBinary` is just a wrapper around `write` that handles the creation of output streams. I can use `write()` in my code if you want but then I'm pretty sure I'll run into the same thing.

**Comment by EdeMeijer** [comment] 2016-11-21 15:16
I tried, and same thing happens.

**Comment by EdeMeijer** [comment] 2016-11-21 15:17
It's not high priority, for now I can work around it by writing the values as floats.

**Comment by raver119** [comment] 2016-11-21 15:19
it's still not a bug.

We just don't have serialization for INDArrays with INT dataType.
That's essentially what happens for you.

It's possible to create that INT-type INDArray, but it's impossible to use it somehow with Ops or BLAS. So serialization isn't set up for it as well.

**Comment by EdeMeijer** [comment] 2016-11-21 15:21
Oh, good to know. I'll stick to floats then. I was just trying to store some statistics that happened to be integers.

**Comment by raver119** [comment] 2016-11-21 15:21
P.s. This way you create INDArray with INT dataType.
```
Nd4j.create(Nd4j.createBuffer(new int[]{1, 2, 3}))
```

**Comment by raver119** [comment] 2016-11-21 23:23
Now, after some more thinking about it, i'd say it's a bug.
Behaviour here shouldn't be misleading for user in any way.

**Comment by EdeMeijer** [comment] 2016-11-22 07:17
Yeah, an exception like 'sorry but saving int typed arrays is not supported' would have been nice.

**Comment by raver119** [comment] 2016-11-27 14:51
No, we'll do it in proper way. If someone needs INT dataType in future, we'll better provide proper ser/de of INT INDArrays right now, and will just add ops support for it, when needed.

**Comment by raver119** [comment] 2016-11-28 20:09
Fix is merged. Serialization works for INT INDArray, attempt to use them with ops causes appropriate exception. On both backends.

**Closed by raver119** 2016-11-28 20:09 UTC
Labels: bug-low_priority
