### ISSUE TITLE
INDArray.put() issue

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#193] opened 2015-07-03 02:03 UTC
I'm trying to put a column vector ones([2,1]) into a matrix zeros([2,3]) in the second column such that:
[[0.0, 0.0, 0.0]		-->	[[0.0, 1.0, 0.0]
 [0.0, 0.0, 0.0]]		--> 	 [0.0, 1.0, 0.0]]

 There are (at least) 3 ways of doing this. Using putColumn() and slice/assign works, but using indexing (assuming I'm using the correct indexing) doesn't.
 
 For example, 
 arr.put(new NDArrayIndex[]{NDArrayIndex.all(),new NDArrayIndex(1)}, col);
 gives
 [[1.0, 1.0, 0.0]
 [0.0, 0.0, 0.0]]
 not
 [[0.0, 1.0, 0.0]
 [0.0, 1.0, 0.0]]
 
Edit: Same result for netlib, java and jblas
 
 ```java
	@Test
	public void putExample(){
		
		INDArray arr = Nd4j.zeros(new int[]{2,3});
		INDArray col = Nd4j.ones(new int[]{2,1});
		
		//3 equivalent ways to do the same thing:
		//[[0.0, 0.0, 0.0]		-->	[[0.0, 1.0, 0.0]
		// [0.0, 0.0, 0.0]]		--> 	 [0.0, 1.0, 0.0]]
//		arr.putColumn(1, col);
//		arr.slice(1, 0).assign(col);
//		arr.put(new NDArrayIndex[]{NDArrayIndex.all(),new NDArrayIndex(1)}, col);
		
		//My way of  thinking: want to assign rows 0..1 inclusive, column 1
		//	-> new NDArrayIndex[]{interval(0,2),new NDArrayIndex(1)}	OR
		//	-> new NDArrayIndex[]{NDArrayIndex.all(),new NDArrayIndex(1)}
		//But both of these don't give the result I want.
		
		System.out.println(arr);
	}
 ```

**Comment by AlexDBlack** [comment] 2015-07-03 02:58
See also below. Same result on jblas, netlib, java backends.
```java
	@Test
	public void putExample2(){
		//Idea: [0,0,0,0] -> [1,1,0,0] 
		INDArray row4 = Nd4j.zeros(4);
		INDArray row2 = Nd4j.ones(2);
		
		//These should all be equivalent?
//		row4.put(new NDArrayIndex[]{new NDArrayIndex(0), new NDArrayIndex(0,1)},row2);	//Output: [1.0, 0.0, 0.0, 0.0]
//		row4.put(new NDArrayIndex[]{new NDArrayIndex(0), interval(0,2)},row2);			//Output: [1.0, 0.0, 0.0, 0.0]
//		row4.put(new NDArrayIndex[]{NDArrayIndex.all(), new NDArrayIndex(0,1)},row2);	//java.lang.IllegalArgumentException: Unable to get linear index >= 2
//		row4.put(new NDArrayIndex[]{NDArrayIndex.all(), interval(0,2)},row2);			//java.lang.IllegalArgumentException: Unable to get linear index >= 2
		
		System.out.println(row4);
	}
```

**Comment by agibsonccc** [comment] 2015-07-03 14:53
So I finally ran this:
  row4.put(new NDArrayIndex[]{NDArrayIndex.all(), new NDArrayIndex(0,1)},row2);   //java.lang.IllegalArgumentException: Unable to get linear index >= 2
        row4.put(new NDArrayIndex[]{NDArrayIndex.all(), NDArrayIndex.interval(0,2)},row2);           //java.lang.IllegalArgumentException: Unable to get linear index 

Both of these should be column vectors not row vectors. I'm going to close this. This is intended behavior. Please re open this otherwise.

**Closed by agibsonccc** 2015-07-03 14:53 UTC
