### ISSUE TITLE
Outer product only works when duplicating vectors beforehand

### ISSUE THREAD

**Issue by slang03** [deeplearning4j/nd4j#2398] opened 2017-12-20 06:10 UTC
#### Issue Description
Took the following steps
 - Create 4x5 matrix X from arange(20)
 - Get i-th column vector
 - Build outer product from xi
 - Build outer product from xi.dup()
 - Expect the same results

This is implemented in the following JUnit test, that fails:

```java
import junit.framework.TestCase;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.factory.Nd4j;
import org.nd4j.linalg.indexing.NDArrayIndex;

public class Test extends TestCase{

  /**
   * Steps:
   * - Create 4x5 matrix X from arange(20)
   * - Get i-th column vector
   * - Build outer product from xi
   * - Build outer product from xi.dup()
   */
  public void test() {
    // 4x5 matrix from arange(20)
    final INDArray X = Nd4j.arange(20).reshape(4,5);
    for (int i=0; i<5; i++){
      // Get i-th column vector
      final INDArray xi = X.get(NDArrayIndex.all(), NDArrayIndex.point(i));
      // Build outer product
      final INDArray outerProduct = xi.mmul(xi.transpose());
      // Build outer product from duplicated column vectors
      final INDArray outerProductDuped = xi.dup().mmul(xi.transpose().dup());
      // Matrices should equal
      final boolean eq = outerProduct.equalsWithEps(outerProductDuped, 1e-5);
      assertTrue(eq);
    }
  }
}
```

I have a strong suspicion, that in the non-duped multiplication, some multiplications happen on the indices instead of the values at the indices.

This could also be the cause of https://github.com/deeplearning4j/nd4j/issues/2374

#### Version Information
* Nd4j version: 0.9.1
* platform information: Ubuntu 16.04, linux-4.10
* CUDA version: 8
* NVIDIA driver version: 384.90

**Comment by raver119** [comment] 2017-12-20 09:42
And, i guess, with F order it passes?

**Comment by slang03** [comment] 2017-12-20 09:51
Just checked, yes it does

**Comment by slang03** [comment] 2017-12-20 09:57
Correction:

It does not. After correcting the multiplication order it fails with F order as well:

```java
import junit.framework.TestCase;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.factory.Nd4j;
import org.nd4j.linalg.indexing.NDArrayIndex;

public class Test extends TestCase{
    
    /**
     * Steps:
     * - Create 4x5 matrix X from arange(20)
     * - Get i-th column vector
     * - Build outer product from xi
     * - Build outer product from xi.dup()
     */
    public void test() {
        // 4x5 matrix from arange(20)
        final INDArray X = Nd4j.arange(20).reshape('f',4,5);
        for (int i=0; i<5; i++){
            // Get i-th column vector
            final INDArray xi = X.get(NDArrayIndex.point(i), NDArrayIndex.all());
            // Build outer product
            final INDArray outerProduct = xi.transpose().mmul(xi);
            // Build outer product from duplicated column vectors
            final INDArray outerProductDuped = xi.transpose().dup().mmul(xi.dup());
            // Matrices should equal
            final boolean eq = outerProduct.equalsWithEps(outerProductDuped, 1e-5);
            assertTrue(eq);
        }
    }
}
```

**Comment by raver119** [comment] 2017-12-20 10:15
Aha. The problem is trivial. only A argument is checked for being a view. B is not. Fix incoming

**Comment by raver119** [comment] 2017-12-20 10:28
Fix merged. Thanks for highlighting/investigating this bug!

**Closed by raver119** 2017-12-20 10:28 UTC
Labels: bug
