### ISSUE TITLE
Crash on Computational Graph training

### ISSUE THREAD

**Issue by oracle1wr** [deeplearning4j/nd4j#1579] opened 2017-01-10 18:47 UTC
Have a computational graph with two RNN inputs and an output. Java crashes after several iterations. 

---------------------------------------------------------------------------------------------------------------------------------------
 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f6c4ca2964b, pid=8539, tid=140106407528192

 JRE version: Java(TM) SE Runtime Environment (8.0_45-b14) (build 1.8.0_45-b14)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [libnd4j.so+0x5264b]  _ZN9functions6scalar15ScalarTransformIfE9transformIN7simdOps3AddIfEEEEvPfiS7_ifS7_x._omp_fn.627+0x19b

---------------------------------------------------------------------------------------------------------------------------------------
Stack: [0x00007f6d1096c000,0x00007f6d10a6d000],  sp=0x00007f6d10a6aaf0,  free space=1018k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libnd4j.so+0x5264b]  _ZN9functions6scalar15ScalarTransformIfE9transformIN7simdOps3AddIfEEEEvPfiS7_ifS7_x._omp_fn.627+0x19b

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 2088  org.nd4j.nativeblas.NativeOps.execScalarFloat(Lorg/bytedeco/javacpp/PointerPointer;ILorg/bytedeco/javacpp/FloatPointer;ILorg/bytedeco/javacpp/FloatPointer;IFLorg/bytedeco/javacpp/FloatPointer;J)V (0 bytes) @ 0x00007f6cf9813463 [0x00007f6cf98133c0+0xa3]
J 2460 C2 org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(Lorg/nd4j/linalg/api/ops/ScalarOp;)V (604 bytes) @ 0x00007f6cf99e22a4 [0x00007f6cf99e1900+0x9a4]
J 2225 C2 org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(Lorg/nd4j/linalg/api/ops/Op;)Lorg/nd4j/linalg/api/ops/Op; (111 bytes) @ 0x00007f6cf98824d0 [0x00007f6cf9882240+0x290]
J 2317 C1 org.nd4j.linalg.api.ndarray.BaseNDArray.addi(Ljava/lang/Number;Lorg/nd4j/linalg/api/ndarray/INDArray;)Lorg/nd4j/linalg/api/ndarray/INDArray; (46 bytes) @ 0x00007f6cf991457c [0x00007f6cf9913ea0+0x6dc]
j  org.nd4j.linalg.api.ndarray.BaseNDArray.add(Ljava/lang/Number;Lorg/nd4j/linalg/api/ndarray/INDArray;)Lorg/nd4j/linalg/api/ndarray/INDArray;+6
j  org.deeplearning4j.examples.recurrent.htn_cn.CNPairsIterator.next(I)Lorg/nd4j/linalg/dataset/api/MultiDataSet;+130
j  org.deeplearning4j.examples.recurrent.htn_cn.CNPairsIterator.next()Lorg/nd4j/linalg/dataset/api/MultiDataSet;+2
j  org.deeplearning4j.examples.recurrent.htn_cn.CNameMatch.main([Ljava/lang/String;)V+481
v  ~StubRoutines::call_stub
j  sun.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+0
j  sun.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+100
j  sun.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+6
j  java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+56
j  com.intellij.rt.execution.application.AppMain.main([Ljava/lang/String;)V+170
v  ~StubRoutines::call_stub

**Comment by raver119** [comment] 2017-01-10 18:58
Show your pom.xml, and code that reproduces this crash.

**Comment by oracle1wr** [comment] 2017-01-10 22:41
Attached java source. I have a standard pom file from DL4J examples, anyway attaching it also.
[pom_and_java_source.zip](https://github.com/deeplearning4j/nd4j/files/697578/pom_and_java_source.zip)

**Comment by raver119** [comment] 2017-01-10 22:43
Great, thanks. But what versions were used there? Your pom.xml uses vars, and i don't see what are they set to

**Comment by raver119** [comment] 2017-01-10 22:44
Also, since you're on linux, please show me result of the following command:
```
ldd --version
```

**Comment by oracle1wr** [comment] 2017-01-10 22:48
ldd --version
>> ldd (Ubuntu EGLIBC 2.19-0ubuntu6.9) 2.19

Here are versions:
        <java.version>1.8</java.version>
        <nd4j.version>0.7.1</nd4j.version>
        <dl4j.version>0.7.1</dl4j.version>
        <datavec.version>0.7.1</datavec.version>
        <arbiter.version>0.7.1</arbiter.version>
        <guava.version>19.0</guava.version>
        <logback.version>1.1.7</logback.version>
        <jfreechart.version>1.0.13</jfreechart.version>
        <jcommon.version>1.0.23</jcommon.version>

**Comment by raver119** [comment] 2017-01-10 22:49
Could you please try 0.7.2 and confirm it's still an issue.

**Comment by oracle1wr** [comment] 2017-01-10 22:59
Yes, I can see the same issue. 

One more piece of data that may be helpful, the crash happens after training score goes below 0;
Completed 40 minibatches of size 32x200 characters
o.d.o.l.ScoreIterationListener - Score at iteration 40 is 0.003159044285685475
o.d.o.l.ScoreIterationListener - Score at iteration 41 is 0.0012823407562427835
o.d.o.l.ScoreIterationListener - Score at iteration 42 is -6.037154743334661E-4
o.d.o.l.ScoreIterationListener - Score at iteration 43 is -0.002499370673563539
o.d.o.l.ScoreIterationListener - Score at iteration 44 is -0.004399751135524599

**Comment by raver119** [comment] 2017-01-10 23:04
So, yes, there's a bug with missing input size validation. I'll fix it. 

It's caused by mismatching shapes of sentenceVectors and return value of sentenceToVec method.

Also, your code:

```
sentenceVector1.add(i, sentenceToVec(sentence1.toString().split("\\s+")));
sentenceVector2.add(i, sentenceToVec(sentence2.toString().split("\\s+")));
...
return new org.nd4j.linalg.dataset.MultiDataSet(new INDArray[]{sentenceVector1, sentenceVector2}, new INDArray[]{labelVector});
```

In this case you don't have sentenceVector updated, second operand is the result. You probably want to use addi instead.

**Comment by oracle1wr** [comment] 2017-01-10 23:10
oh, got it.
Thanks for looking to an issue and proposing fixes to my code.

**Comment by raver119** [comment] 2017-01-10 23:15
Issue is fixed on current master now.

Thanks for reporting this one

**Closed by raver119** 2017-01-10 23:15 UTC
Labels: bug
