### ISSUE TITLE
nd4j-jcublas initialization error

### ISSUE THREAD

**Issue by Ingwar** [deeplearning4j/nd4j#535] opened 2015-12-13 12:08 UTC
Hello, I'm getting the following error  from the nd4j-jcublas:
```
java.io.IOException: Could not create .ptx file: /tmp/kernels/float/add_strided.cu(12): error: too many arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_00005c16_00000000-299_add_strided.cpp1.ii".

	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:282)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:317)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:194)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.load(KernelFunctionLoader.java:160)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.getInstance(KernelFunctionLoader.java:77)
	at org.nd4j.linalg.jcublas.SimpleJCublas.init(SimpleJCublas.java:110)
	at org.nd4j.linalg.jcublas.SimpleJCublas.<clinit>(SimpleJCublas.java:65)
	at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.<init>(JCudaExecutioner.java:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4551)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4499)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:140)
	at org.deeplearning4j.nn.conf.MultiLayerConfiguration$Builder.build(MultiLayerConfiguration.java:282)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$ListBuilder.build(NeuralNetConfiguration.java:161)
	at 
```

It looks like that the actual error is produced by the following call to the nvcc:
```
nvcc -g -G  --include-path /tmp/kernels/float/  -ptx  /tmp/kernels/float/std_strided.cu /tmp/kernels/float/var_strided.cu /tmp/kernels/float/bias_strided.cu /tmp/kernels/float/add_strided.cu /tmp/kernels/float/sub_strided.cu /tmp/kernels/float/mul_strided.cu /tmp/kernels/float/div_strided.cu /tmp/kernels/float/rsub_strided.cu /tmp/kernels/float/rdiv_strided.cu /tmp/kernels/float/neg_strided.cu /tmp/kernels/float/tanh_strided.cu /tmp/kernels/float/exp_strided.cu /tmp/kernels/float/sigmoid_strided.cu /tmp/kernels/float/log_strided.cu /tmp/kernels/float/floor_strided.cu /tmp/kernels/float/ceil_strided.cu /tmp/kernels/float/abs_strided.cu /tmp/kernels/float/pow_strided.cu /tmp/kernels/float/sqrt_strided.cu /tmp/kernels/float/sign_strided.cu /tmp/kernels/float/sum_strided.cu /tmp/kernels/float/prod_strided.cu /tmp/kernels/float/norm1_strided.cu /tmp/kernels/float/norm2_strided.cu /tmp/kernels/float/normmax_strided.cu /tmp/kernels/float/max_strided.cu /tmp/kernels/float/min_strided.cu /tmp/kernels/float/mean_strided.cu /tmp/kernels/float/softmax_strided.cu /tmp/kernels/float/add_scalar.cu /tmp/kernels/float/sub_scalar.cu /tmp/kernels/float/mul_scalar.cu /tmp/kernels/float/div_scalar.cu /tmp/kernels/float/rsub_scalar.cu /tmp/kernels/float/rdiv_scalar.cu /tmp/kernels/float/cosinesimilarity_strided.cu /tmp/kernels/float/manhattan_strided.cu /tmp/kernels/float/euclidean_strided.cu /tmp/kernels/float/lessthan_scalar.cu /tmp/kernels/float/lessthanorequal_scalar.cu /tmp/kernels/float/gt_strided.cu /tmp/kernels/float/lt_strided.cu /tmp/kernels/float/greaterthan_scalar.cu /tmp/kernels/float/greaterthanorequal_scalar.cu /tmp/kernels/float/binomial.cu /tmp/kernels/float/binomial_scalar.cu /tmp/kernels/float/uniform.cu /tmp/kernels/float/equals_scalar.cu /tmp/kernels/float/notequals_scalar.cu /tmp/kernels/float/max_scalar.cu /tmp/kernels/float/min_scalar.cu /tmp/kernels/float/eps_strided.cu /tmp/kernels/float/setvalorless_scalar.cu /tmp/kernels/float/copy_strided.cu /tmp/kernels/float/setrange_strided.cu /tmp/kernels/float/round_strided.cu /tmp/kernels/float/set_scalar.cu --output-directory /tmp/kernels/float/
```

which produces the following error:
```
/tmp/kernels/float/add_strided.cu(12): error: too many arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_0000629a_00000000-299_add_strided.cpp1.ii".
```

Indeed, if you look at the call to the `transform` at the [add_strided.cu](https://github.com/deeplearning4j/nd4j/blob/master/nd4j-jcublas-parent/nd4j-jcublas-kernels/src/main/resources/kernels/float/add_strided.cu#L12), you could see that `transform` is called with 11arguments whereas in [pairwise_transform.h](https://github.com/deeplearning4j/nd4j/blob/master/nd4j-jcublas-parent/nd4j-jcublas-kernels/src/main/resources/kernels/float/pairwise_transform.h#L7) it's defined with 10 arguments.

**Comment by raver119** [comment] 2015-12-13 12:14
This is going to be fixed in rc3.8 as part of major cuda code overhaul.
3.8 should be coming within few nearest days.

**Comment by Ingwar** [comment] 2015-12-13 12:14
[Here](http://pastebin.com/f8Eazkqe) is more detailed logs

**Comment by Ingwar** [comment] 2015-12-13 12:15
Thank you, I'm glad to hear this.

**Comment by newikov** [comment] 2015-12-28 20:52
Hi, 
I have the same problem actually. Have you managed to fix it somehow by now? Seems that rc3.8 is not out yet. 
Would appreciate any help.

**Comment by newikov** [comment] 2015-12-28 20:54
This is what i get 

java.io.IOException: Could not create .ptx file: C:/Users/Admin/AppData/Local/Temp/kernels/float/add_strided.cu(12): error: too many arguments in function call

1 error detected in the compilation of "C:/Users/Admin/AppData/Local/Temp/tmpxft_00002a78_00000000-318_add_strided.cpp1.ii".

	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:282)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:317)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:194)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.load(KernelFunctionLoader.java:160)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.getInstance(KernelFunctionLoader.java:77)
	at org.nd4j.linalg.jcublas.SimpleJCublas.init(SimpleJCublas.java:110)
	at org.nd4j.linalg.jcublas.SimpleJCublas.<clinit>(SimpleJCublas.java:65)
	at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.<init>(JCudaExecutioner.java:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4551)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4499)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:140)
	at com.newikov.neuralnetworks.arquitecture.TestNd4JCuda.main(TestNd4JCuda.java:11)
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nd4j.linalg.jcublas.ops.executioner.JCudaExecutioner.<init>(JCudaExecutioner.java:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4551)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4499)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:140)
	at com.newikov.neuralnetworks.arquitecture.TestNd4JCuda.main(TestNd4JCuda.java:11)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Could not create .ptx file: C:/Users/Admin/AppData/Local/Temp/kernels/float/add_strided.cu(12): error: too many arguments in function call

1 error detected in the compilation of "C:/Users/Admin/AppData/Local/Temp/tmpxft_00001428_00000000-318_add_strided.cpp1.ii".

	at org.nd4j.linalg.jcublas.SimpleJCublas.<clinit>(SimpleJCublas.java:67)
	... 10 more
Caused by: java.lang.RuntimeException: java.io.IOException: Could not create .ptx file: C:/Users/Admin/AppData/Local/Temp/kernels/float/add_strided.cu(12): error: too many arguments in function call

1 error detected in the compilation of "C:/Users/Admin/AppData/Local/Temp/tmpxft_00001428_00000000-318_add_strided.cpp1.ii".

	at org.nd4j.linalg.jcublas.SimpleJCublas.init(SimpleJCublas.java:112)
	at org.nd4j.linalg.jcublas.SimpleJCublas.<clinit>(SimpleJCublas.java:65)
	... 10 more
Caused by: java.io.IOException: Could not create .ptx file: C:/Users/Admin/AppData/Local/Temp/kernels/float/add_strided.cu(12): error: too many arguments in function call

1 error detected in the compilation of "C:/Users/Admin/AppData/Local/Temp/tmpxft_00001428_00000000-318_add_strided.cpp1.ii".

	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:282)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:317)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:194)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.load(KernelFunctionLoader.java:160)
	at org.nd4j.linalg.jcublas.SimpleJCublas.init(SimpleJCublas.java:110)
	... 11 more

**Comment by agibsonccc** [comment] 2015-12-28 23:48
Wait till rc3.8. If you have any issues afterwards we'll support it. Thanks!

**Closed by agibsonccc** 2015-12-28 23:48 UTC

**Comment by agibsonccc** [comment] 2016-01-08 17:27
We pushed back the release. Please come in to gitter for any further inquiries on gpus for now.
