### ISSUE TITLE
Not using all devices when running on multiple GPUs

### ISSUE THREAD

**Issue by jknair** [deeplearning4j/nd4j#145] opened 2015-06-04 11:51 UTC
Was trying out really large matrix multipilication on a system with multiple GPUs. I could only see the GPU RAM for one device filling up and eventually 
```jcuda.CudaException: CUBLAS_STATUS_ALLOC_FAILED```. Any way to use the other available cuda devices seamlessly ?

**Comment by agibsonccc** [comment] 2015-06-05 15:12
Is this based on what's in master or maven central? I haven't had issues with this.

It would be great if you can capture the output from nvidia-smi and post a screenshot or 2 of it running.

I'd also like to hear how your cards are setup. Have you ran multiple GPUs before?

**Comment by turingsmart** [comment] 2015-06-08 11:05
version of nd4j being used :
<dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-jcublas-6.5</artifactId>
            <version>0.0.3.5.5.2</version>
</dependency>

The screenshot when the below code is run for queries = 1000

Code:
public static int million = 1000000;
public static int tenMillion = million * 10;
public static int dimensions = 200;

private static long gpuTest(int queries) {

        double[][] kwdVectors = new double[million][dimensions];
        for (int i = 0; i < million; i++) {
            for (int j = 0; j < dimensions; j++) {
                kwdVectors[i][j] = Math.random();
            }
        }

        double[][]queryVectors = new double[queries][dimensions];
        for (int i = 0; i < queries; i++) {
            for (int j = 0; j < dimensions; j++) {
                queryVectors[i][j] = Math.random();
            }
        }

        INDArray kwdVecInd = Nd4j.create(kwdVectors).transpose();
        INDArray queryInd = Nd4j.create(queryVectors);
        return multiplyArrays(queryInd, kwdVecInd);
    }

Exception:
jcuda.CudaException: CUBLAS_STATUS_ALLOC_FAILED
	at jcuda.jcublas.JCublas.checkResult(JCublas.java:139)
	at jcuda.jcublas.JCublas.cublasAlloc(JCublas.java:257)
	at org.nd4j.linalg.jcublas.SimpleJCublas.alloc(SimpleJCublas.java:360)
	at org.nd4j.linalg.jcublas.SimpleJCublas.gemm(SimpleJCublas.java:744)
	at org.nd4j.linalg.jcublas.JCublasWrapper.gemm(JCublasWrapper.java:198)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmuli(BaseNDArray.java:2517)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mmul(BaseNDArray.java:2345)
	at HVK.CudaTestTimes.multiplyArrays(CudaTestTimes.java:74)
	at HVK.CudaTestTimes.gpuTest(CudaTestTimes.java:68)
	at HVK.CudaTestTimes.main(CudaTestTimes.java:45)
![screenshot from 2015-06-08 15 13 39](https://cloud.githubusercontent.com/assets/1404414/8033487/54306a66-0dfc-11e5-9b4e-f30a1533dfb5.png)

**Comment by agibsonccc** [comment] 2015-06-08 11:08
Could you try the latest version of nd4j? That with cublas 7.0 is the
version that handles multiple gpus.

**Comment by agibsonccc** [comment] 2015-06-11 01:56
Closing this as can't reproduce with newest version.

**Closed by agibsonccc** 2015-06-11 01:56 UTC

**Comment by jknair** [comment] 2015-06-11 08:26
We are having issues installing cuda 7 on the box. Will let you know once we test it out. @agibsonccc  which version do you want us to test it out on ?

**Comment by agibsonccc** [comment] 2015-06-11 12:38
Great! Master is fine. We will be deploying this to maven central shortly.
ᐧ

**Comment by turingsmart** [comment] 2015-06-11 15:54
It seems now it is using all the GPUs with cuda 7 and latest jcublas maven version.
However, I am getting this exception...
```
java.lang.IllegalArgumentException: initialCapacity: -294967296 (expectd: 0+)
	at io.netty.buffer.AbstractByteBufAllocator.validate(AbstractByteBufAllocator.java:196)
	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:135)
	at io.netty.buffer.Unpooled.buffer(Unpooled.java:141)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:147)
	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:107)
	at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:48)
	at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createFloat(CudaDataBufferFactory.java:41)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:566)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:183)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:200)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:374)
	at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:231)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:176)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:193)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3109)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:2500)
```

Code :
VectorA dimensions : 1000*200
VectorB dimensions : 200*1000000
```java
public static synchronized long multiplyArrays(INDArray vectorA, INDArray vectorB) {
        INDArray mul = Nd4j.create(vectorA.rows(), vectorB.columns());
    }
```

**Comment by agibsonccc** [comment] 2015-06-11 17:49
Thanks for the test case. Will take a look at this. Something similar was
reported for dl4j. This has something to do with the bytebuffer storage.

**Comment by jknair** [comment] 2015-06-12 08:46
@agibsonccc hey can you point us to the issue reported so we can keep an eye out on the fix :)
