### ISSUE TITLE
ND4J is not compatible with Spark's next-gen Kryo serializer (throws NPEs)

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/nd4j#949] opened 2016-05-19 02:23 UTC
Upgraded to latest `3.10-SNAPSHOT` and getting this in my cluster:

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 38 in stage 0.0 failed 4 times, most recent failure: Lost task 38.3 in stage 0.0 (TID 64, slave6.cluster): java.lang.NullPointerException
    at org.nd4j.linalg.api.shape.Shape.rank(Shape.java:1387)
    at org.nd4j.linalg.api.ndarray.BaseNDArray.rank(BaseNDArray.java:3917)
```

Full stack trace: https://gist.github.com/crockpotveggies/75a0f78bbe33b024f214c17fbd53d22e

I've already provided a dataset to @agibsonccc and a debug repo is available here: https://github.com/crockpotveggies/dl4j-full-stack-debug

**Comment by crockpotveggies** [comment] 2016-05-20 00:44
Correction, I am also experiencing this on the `rc3.9` release as well.

**Comment by AlexDBlack** [comment] 2016-05-20 08:16
Anything you can give me to reproduce this? I ran the spark examples earlier, and didn't see this come up.

**Comment by crockpotveggies** [comment] 2016-05-20 14:45
I will PM the dataset I'm using to you via Gitter.

**Comment by crockpotveggies** [comment] 2016-05-20 16:54
Dataset sent.

**Comment by crockpotveggies** [comment] 2016-05-20 23:23
Core issue identified. ND4J is not compatible with Spark's next-gen Kryo serializer. Going to update the name of this issue.

**Comment by AlexDBlack** [comment] 2016-05-21 06:06
Confirmed: default Kryo serialization (tested with v3.0.3) completely messes up the serialization of INDArrays (only tested with nd4j-native, very likely exactly the same with cuda).
We get null fields out for both the shapeInformation and the data; I suspect the field-by-field copy won't be safe for the linearStride either (might not be defined on a view, but could be fine on the deserialized non-view array).

This reproduces the issue:
```java
    public static void main(String[] args){
        INDArray before = Nd4j.linspace(1,10,10);

        Kryo kryo = new Kryo();
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        Output output = new Output(baos);
        kryo.writeObject(output, before);
        output.close();

        byte[] bytes = baos.toByteArray();

        Input input = new Input(new ByteArrayInputStream(bytes));
        INDArray after = kryo.readObject(input, NDArray.class);
        input.close();

        System.out.println(before);
        System.out.println(after);
    }
```


![image](https://cloud.githubusercontent.com/assets/2360237/15446765/d69afcc2-1f6d-11e6-88ae-8af0d3895e5a.png)

**Comment by AlexDBlack** [comment] 2016-05-21 06:16
Only good option I think is to add Kryo as a dependency (don't really like that, but seems necessary) and then implement custom serialization there
https://github.com/EsotericSoftware/kryo/blob/master/README.md#kryoserializable

@crockpotveggies was this something you were going to look into fixing?

**Comment by agibsonccc** [comment] 2016-05-21 06:20
Since this is spark specific any way we could add kryo as an extra dep for nd4j on spark?

**Comment by AlexDBlack** [comment] 2016-05-21 06:26
I don't think so, if we use the KryoSerializable interface - that has to be defined on the NDArray methods (I guess BaseNDArray).

Only other option I'm aware of (also doesn't require Kryo as a dependency) is to manually register things: 
for example,
kryo.register(INDArray.class, new JavaSerializer());    //Java-based serialization
kryo.register(INDArray.class, new OurCustomSerializer());   //Custom serialization

In both cases, user has to remember to actually do this, or they will run into cryptic NPEs like the above. So I don't really like that option either (risks wasting a lot of time for users).

**Comment by agibsonccc** [comment] 2016-05-21 06:31
What about adding it to Dl4jSpark and adding it in the static initializer?

**Comment by AlexDBlack** [comment] 2016-05-21 06:37
That'll solve the problem for probably 95% of users. Only ones left then are those who are using ND4J with Spark and Kryo, but *not* as part of DL4J. Which will happen, but not often. Maybe that plus some docs on how to manually register things is good enough.

**Comment by Habitats** [comment] 2016-05-21 10:49
I had this issue some weeks ago, and forgot to actually make the issue. Anyway, I made an attempt at making a custom INDArray serializer, and ran into trouble. Reason was that the kryo-instance itself isn't visible to spark (`kryo.register() cannot be used directly)`, so it seems you have to override the main serializer. When I did this, the serializer forgot how to do simple things like Ints and Doubles, and all other built in classes. Maybe it can be solved by extending the "standard" one somehow?

**Comment by AlexDBlack** [comment] 2016-05-21 12:03
hm, I had assumed you'd be able to configure the kryo serialization (that seems like a very common use case), but yeah, looks like that isn't possible (seems like a poor design to me...). Seems like the only thing you can do is register classes (using default serializer) but not actually specify the kryo serializer to use for a given class.


Anyway, as @Habitats suggested, you can set the spark serializer in spark config, and overriding the newKryo() method in the KryoSerializer.scala seems feasible:
```java
    public class TestSerializer extends KryoSerializer{
        public TestSerializer(SparkConf conf) {
            super(conf);
        }

        @Override
        public Kryo newKryo(){
            Kryo kryo = super.newKryo();
            kryo.register(INDArray.class, new JavaSerializer());
            return kryo;
        }
    }
```

I haven't tested serialization with that, but it initializes OK and returns an instance of the right class using
Serializer serializer = sc.env().serializer();
SerializerInstance instance = serializer.newInstance();

Downside here is that to do all this without manual user intervention, you'd need to capture the SparkConfig before it is used to create a SparkContext (I assume changes won't take effect once SparkContext is initialized). Which I doubt is even possible.
As for getting a Kryo object at runtime: that's possible too, but there's no way to propagate changes from it to all Kryo instances (let alone to instances outside of the driver). Kryo instances aren't thread safe, so we'll have a bunch in any Spark job: https://github.com/EsotericSoftware/kryo#threading
```java
        KryoSerializer serializer = (KryoSerializer) sc.env().serializer();
        KryoSerializerInstance instance = (KryoSerializerInstance) serializer.newInstance();
        Kryo kryo1 = serializer.newKryo();
        Kryo kryo2 = instance.borrowKryo();
```

So it seems like we are back in the same place: either...
1. Force users to manually specify our custom Kryo serializer in the spark config, any time they want to use Kryo (bad), or
2. Add Kryo as a dependency in ND4J and implement the KryoSerializable interface (bad, but maybe less bad?)

**Comment by agibsonccc** [comment] 2016-05-22 14:16
I'm actually all  for 1 as long as we give it to them. A reasonably documented "how to setup a spark job" should be enough..

**Comment by agibsonccc** [comment] 2016-05-22 14:32
https://github.com/deeplearning4j/nd4j/pull/969   + http://stackoverflow.com/questions/36144618/spark-kryo-register-a-custom-serializer Let me know if this is enough.

**Comment by agibsonccc** [comment] 2016-05-23 11:39
I'm closing this. Open it again if it's a problem.

**Comment by crockpotveggies** [comment] 2016-05-25 01:30
Still experiencing issues with this. It appears that when you use a custom Registrator, Kryo wants you to define *all* the classes that are going to be used, which may be plenty...

`NoClassFoundError: Could not initialize class org.nd4j.linalg.factory.Nd4j`

and

`Error constructing instance of class: org.nd4j.linalg.dataset.DataSet`

![screen shot 2016-05-24 at 6 27 21 pm](https://cloud.githubusercontent.com/assets/1445295/15525270/7c6365e2-21dd-11e6-9583-0fc5e59924f3.png)

Suggest this is re-opened.

**Comment by crockpotveggies** [comment] 2016-05-25 17:12
My next step is to try and define a full object graph that will be used with Kryo. It looks like anything that is going to be passed between Spark nodes is going to be on that list.

**Comment by AlexDBlack** [comment] 2016-05-26 05:29
So it looks like there's two entirely separate mechanisms/solutions here.

**Option 1**: The MyKryoSerializer extends KryoSerializer approach
This is set using:
sparkConf.set("spark.serializer", "my.custom.Serializer");
-> This should work, but it's not especially flexible - user might need a different custom serializer for other reasons


**Option 2**: Registrator plus custom serializer approach:
sparkConf.set("spark.serializer", "org.apache.spark.serializer.KryoSerializer");
sparkConf.set("spark.kryo.registrator", "my.custom.Registrator");	//We don't have a registrator yet, but it's easy to make (see below

```java
public class TestRegistrator implements KryoRegistrator {
    @Override
    public void registerClasses(Kryo kryo) {
//        kryo.register(INDArray.class, new Nd4jSerializer());    //DOESN'T WORK - getting same NPE problem
        kryo.register(org.nd4j.linalg.cpu.nativecpu.NDArray.class, new Nd4jSerializer());   //DOES work, but is backend specific
    }
}
```

I'm not seeing any issues with DataSet, or anything else for that matter using option 2. Spark examples (tested local only) seem to work fine with only the above.

One simple solution to the backend specific problem is to do the following:
- Have a static instance of the Registrator class that is always used
- Use reflection to find out what classes implement the INDArray interface, and register all of them with the Nd4jSerializer

**Comment by agibsonccc** [comment] 2016-05-26 05:31
@AlexDBlack the registration could use reflection to discover sub classes
and use that for the registration instead. There is a way to discover the
backend.

**Comment by AlexDBlack** [comment] 2016-05-26 05:32
Yeah, I was thinking reflection on INDArray interface is easiest and should be fine. Wanted to check first. I assume there's no reference to the INDArray implementation class available via Nd4j or anything?

**Comment by agibsonccc** [comment] 2016-05-26 05:36
We could? I was just thinking the reflections library.

**Comment by AlexDBlack** [comment] 2016-05-26 05:43
One othe problem: both the the KryoRegistrator interface and the KryoSerializer class (i.e., options 1 and 2) are part of **spark** not part of the Kryo library.

So either approach requires spark as a dependency somewhere.
I guess we add Spark as a dependency for nd4j-kryo (with <scope>provided</scope> presumably)?

**Comment by AlexDBlack** [comment] 2016-05-26 09:36
PR here: https://github.com/deeplearning4j/nd4j/pull/974
This should hopefully fix it. See comments there on usage.

**Closed** 2016-05-28 14:30 UTC
