### ISSUE TITLE
deep_mnist issue

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#2630] opened 2018-02-13 07:19 UTC
deep_mnist graph has 2 fundamental issues

1) It uses rng internally, so unless we're going to provide exactly the same rng, there will be difference in results.
2) Test itself is broken - it doesn't provide all necessary placeholders values, so it NaNs out during execution due to division by zero etc.

**Comment by raver119** [comment] 2018-02-13 07:20
p.s. let's fix problem nr. 2, and ignore problem nr. 1 for now.
We clearly should throw clear exception in case of non-resolved placeholders

**Comment by eraly** [comment] 2018-02-14 01:53
It closed automatically when I put in the link in the subject of the PR. Please confirm fix. I added the placeholder needed for dropout.

**Comment by raver119** [comment] 2018-02-20 07:40
Result-only check passes now, intermediate check fails. Usually that means something is off with test.

**Comment by eraly** [comment] 2018-02-20 22:13
The intermediate nodes that are failing are due to the RandomUniform op (which I am guessing is due the difference in rng)

Here is the node:
```
node {
  name: "dropout/dropout/random_uniform/RandomUniform"
  op: "RandomUniform"
  input: "dropout/dropout/Shape"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "seed"
    value {
      i: 0
    }
  }
  attr {
    key: "seed2"
    value {
      i: 0
    }
  }
}
```

I can add exceptions for these in the test framework.

**Comment by eraly** [comment] 2018-02-21 19:22
Confirmed. Closing.

**Closed** 2018-02-25 01:39 UTC
Labels: bug
