### ISSUE TITLE
a Transforms.atan2 to work on two INDArrays elementwise

### ISSUE THREAD

**Issue by lukeczapla** [deeplearning4j/nd4j#1902] opened 2017-07-01 22:44 UTC
#### Issue Description

I would like an atan2 function to act on two INDArray and calculate their atan2 elementwise.  Right now I'm using Transforms.atan() and thinking of how to correct for the quadrant.

#### Version Information
ND4J 0.8.0

#### Contributing

As mentioned, I think there might be a way to use other Transforms to fix the regular atan.  If the x component is negative I think that's where it needs a simple transformation, either adding or subtracting PI depending on whether y is positive or negative.

Code example: https://gist.github.com/lukeczapla/799d6a72e9185cde286718d94aba9d59

**Comment by raver119** [comment] 2017-07-02 14:15
Implemented and merged: https://github.com/deeplearning4j/nd4j/commit/4b9c56c7445d0e2aa4aab247a0129aa8b706b1fc

**Comment by lukeczapla** [comment] 2017-07-03 05:02
It is not working for me.  I get this error occasionally:

m.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise

**Comment by raver119** [comment] 2017-07-03 18:14
As we now know it's caused by broken snapshots for macOS. Closing this issue now. It will be working as intended once snapshots are back.

**Closed by raver119** 2017-07-03 18:14 UTC
Labels: enhancement
