### ISSUE TITLE
Error building nd4j lib on PI 3 or cross-compiling for PI 

### ISSUE THREAD

**Issue by rvanderwerf** [deeplearning4j/nd4j#2829] opened 2018-04-13 04:19 UTC
#### Issue Description

Please describe your issue, along with:
following the guide to compile for the PI I am getting the following error while running:  ./buildnativeoperations.sh -o linux-armhf

I get the following error. I made sure when cross compiling I am using the $ENV{HOME}/raspberrypi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc in pi.cmake or the local version on the pi itself but I get the same error. If I open that link.txt file to remove the -lFALSE it just regenerates it when running it again.

[100%] Linking CXX shared library libnd4j.so
cd /home/pi/github/libnd4j/blasbuild/cpu/blas && /usr/bin/cmake -E cmake_link_script CMakeFiles/nd4j.dir/link.txt --verbose=1
/usr/bin/arm-linux-gnueabihf-g++  -fPIC  -Wall -O3 -Wl,-rpath,$ORIGIN/ -march=armv7-r -fopenmp -Wall -O3 -std=c++11 -fassociative-math -funsafe-math-optimizations  -shared -Wl,-soname,libnd4j.so -o libnd4j.so CMakeFiles/nd4j.dir/cpu/NativeBlas.cpp.o CMakeFiles/nd4j.dir/cpu/NativeOps.cpp.o -lFALSE 
/usr/bin/ld: cannot find -lFALSE
collect2: error: ld returned 1 exit status
blas/CMakeFiles/nd4j.dir/build.make:123: recipe for target 'blas/libnd4j.so' failed

#### Version Information
latest github repo as if 9-12-15
Please indicate relevant versions, including, if relevant:

* Deeplearning4j version - latest github master
* platform information (OS, etc): 4.9.35-v7+ #1014 SMP
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
* CUDA version, if used
* NVIDIA driver version, if in use

also on cross compile machine getting same error:
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.1
DISTRIB_CODENAME=serena
DISTRIB_DESCRIPTION="Linux Mint 18.1 Serena"

**Comment by saudet** [comment] 2018-04-13 04:34
I'll close this as duplicate of https://github.com/deeplearning4j/libnd4j/issues/700
The build could use some work, yes. 
Please post on that thread, thanks!

**Closed by saudet** 2018-04-13 04:34 UTC
