### ISSUE TITLE
Batch inference for ParagraphVectors

### ISSUE THREAD

**Issue by oliverdain** [deeplearning4j/nd4j#1638] opened 2017-02-08 21:51 UTC
I need to do inference for a whole bunch of documents. Currently there's no batch inference available so I'm just calling the following for each document:

                val inferred = doc2Vec.inferVector(it)
                val label = doc2Vec.nearestLabels(it, 1).first()
                val labelVec = doc2Vec.lookupTable.vector(label)
                val similarity = Transforms.cosineSim(inferred, labelVec)

It ends up taking an order of magnitude longer to do the inference on `n` documents than it took to train a model on `n` documents.

**Comment by oliverdain** [comment] 2017-02-09 00:32
Just a little data here. I just trained a model. The training took 2 minutes and 18 seconds. I then ran the exact same items though the inference above (I know that's not necessary as inference has already been done - just doing a benchmark) and that took just over an hour.

In the Gitter chat (https://gitter.im/deeplearning4j/deeplearning4j?at=589b924ede50490822a3a16f) you said that you'd try to implement a batch as described in this bug. However, in the meantime we're spending lots of $ on EC2/EMR to do hyperparameter search and such and the vast majority of that time is going to the inference here. Is there any short-term workaround to make this faster, even by a factor of 2 or 3? Apparently `ParagraphVectors` isn't thread safe but we could definitely construct one/thread - I just don't know how to make copies of trained model. Any advice?

**Comment by raver119** [comment] 2017-02-12 12:12
Your blocker isn't an inference. Your blocker is tokenization phase.

Batching + callbacks, probably Future-like callbacks might be an option here.

**Comment by raver119** [comment] 2017-02-12 12:25
Actually yes. I'll provide Future callback now for batched inference. Tokenization will be handled in parallel, inference will be kept as-is, since i know it will utilize any number of cores available anyway.

**Comment by raver119** [comment] 2017-02-12 12:57
here's prototype in my not-yet-merged branch: https://github.com/deeplearning4j/deeplearning4j/blob/f55eca8fc7823e46dee97c7c9129b3dee6da7ab1/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/paragraphvectors/ParagraphVectors.java#L238-L238

I'll test it now, and if it'll be ok - will merge.

**Comment by raver119** [comment] 2017-02-12 14:11
I've added blind Future<INDArray>, for cases when relation between document & resulting INDArray will be handled by end-user.

**Comment by raver119** [comment] 2017-02-12 15:30
Ah, and sure - don't forget about bottleneck caused by IO, if you're reading your documents from anything but the RAM. In case of training, we're trying to hide that by using multiple parallel models hidden internally. But during inference that's going to be your responsibility.

**Comment by raver119** [comment] 2017-02-12 22:01
Ugh. No. Fast fix won't help here. Random reinit happens there :(

**Comment by raver119** [comment] 2017-02-22 20:04
Implemented and merged

**Closed by raver119** 2017-02-22 20:04 UTC
Labels: enhancement
