### ISSUE TITLE
Filling a tensor from a bigger flatten vector run into an exception

### ISSUE THREAD

**Issue by c0der1337** [deeplearning4j/nd4j#146] opened 2015-06-04 23:23 UTC
INDArray flat = Nd4j.toFlattened(Nd4j.arange(0,9));
		INDArray wtensor = Nd4j.zeros(new int[]{2,3,3}) ;
		for (int i = 0; i < wtensor.length(); i++) {
			wtensor.putScalar(i, i);
		}
//not working:
		System.out.println(wtensor);
		for (int i = 0; i < wtensor.length(); i++) {
			wtensor.putScalar(i, flat.getDouble(i));
		}
		System.out.println(wtensor);

Output:
[[[0.0, 6.0, 12.0]
 [2.0, 8.0, 14.0]
  ,[4.0, 10.0, 16.0]]
[[1.0, 7.0, 13.0]
 [3.0, 9.0, 15.0]
  ,[5.0, 11.0, 17.0]]

java.lang.IllegalArgumentException: Illegal index 9 derived from 9 with offset of 0 and stride of 1
	at org.nd4j.linalg.api.ndarray.BaseNDArray.linearIndex(BaseNDArray.java:2693)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:2975)
	at Run_NTN.main(Run_NTN.java:47)

**Comment by agibsonccc** [comment] 2015-06-05 15:14
You should use linearView() with put scalar. You can use indexing here. Either way you're using it wrong here.

You are filling a tensor and trying to do it with a 2d array while iterating over the whole length (this will throw an exception because you are treating it as a vector rather than as 3d. I'm closing this. This is related to misuse not a bug.

**Closed by agibsonccc** 2015-06-05 15:14 UTC
