### ISSUE TITLE
Crash on Amazon Linux AMI with NVIDIA GRID GPU with nd4j-cuda-7.5 backend; works with native

### ISSUE THREAD

**Issue by pwhitey86** [deeplearning4j/nd4j#1307] opened 2016-09-28 21:07 UTC
I am running a dl4j based app on an Amazon Linux AMI with NVIDIA GRID GPU Driver node and get a `java.lang.IllegalStateException: MemcpyAsync H2H failed` The code runs fine on native.

Here is full stderr:

This is the `pom.xml`
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>dl4jaloo</groupId>
    <artifactId>1</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <nd4j.backend>nd4j-cuda-7.5</nd4j.backend>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <shadedClassifier>bin</shadedClassifier>
        <java.version>1.8</java.version>
        <nd4j.version>0.6.0</nd4j.version>
        <dl4j.version>0.6.0</dl4j.version>
        <datavec.version>0.6.0</datavec.version>
        <arbiter.version>0.6.0</arbiter.version>
        <guava.version>19.0</guava.version>
        <jfreechart.version>1.0.13</jfreechart.version>
        <maven-shade-plugin.version>2.4.3</maven-shade-plugin.version>
        <exec-maven-plugin.version>1.4.0</exec-maven-plugin.version>
        <junit.version>4.12</junit.version>
        <slf4j.version>1.7.5</slf4j.version>
        <math3.version>3.6.1</math3.version>
        <csv.version>1.4</csv.version>
        <jackson.version>2.5.1</jackson.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.nd4j</groupId>
                <artifactId>nd4j-native</artifactId>
                <version>${nd4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.nd4j</groupId>
                <artifactId>nd4j-cuda-7.5</artifactId>
                <version>${nd4j.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <!-- ND4J backend. You need one in every DL4J project. Normally define artifactId as either "nd4j-native-platform" or "nd4j-cuda-7.5-platform" -->
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>${nd4j.backend}</artifactId>
        </dependency>

        <!-- Core DL4J functionality -->
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>${dl4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-nlp</artifactId>
            <version>${dl4j.version}</version>
        </dependency>

        <!-- deeplearning4j-ui is used for HistogramIterationListener + visualization: see http://deeplearning4j.org/visualization -->
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-ui</artifactId>
            <version>${dl4j.version}</version>
        </dependency>

        <!-- Force guava versions for using UI/HistogramIterationListener -->
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>${guava.version}</version>
        </dependency>

        <!-- datavec-data-codec: used only in video example for loading video data -->
        <dependency>
            <artifactId>datavec-data-codec</artifactId>
            <groupId>org.datavec</groupId>
            <version>${datavec.version}</version>
        </dependency>

        <!-- Used in the feedforward/classification/MLP* and feedforward/regression/RegressionMathFunctions example -->
        <dependency>
            <groupId>jfree</groupId>
            <artifactId>jfreechart</artifactId>
            <version>${jfreechart.version}</version>
        </dependency>

        <!-- Arbiter: used for hyperparameter optimization examples -->
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>arbiter-deeplearning4j</artifactId>
            <version>${arbiter.version}</version>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-math3</artifactId>
            <version>${math3.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-csv</artifactId>
            <version>${csv.version}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>${jackson.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>${exec-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <executable>java</executable>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>${maven-shade-plugin.version}</version>
                <configuration>
                    <shadedArtifactAttached>true</shadedArtifactAttached>
                    <shadedClassifierName>${shadedClassifier}</shadedClassifierName>
                    <createDependencyReducedPom>true</createDependencyReducedPom>
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <exclude>org/datanucleus/**</exclude>
                                <exclude>META-INF/*.SF</exclude>
                                <exclude>META-INF/*.DSA</exclude>
                                <exclude>META-INF/*.RSA</exclude>
                            </excludes>
                        </filter>
                    </filters>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>reference.conf</resource>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
        </plugins>

        <resources>
            <resource>
                <filtering>false</filtering>
                <directory>src/main/resources</directory>
                <targetPath>${project.build.directory}</targetPath>
                <includes>
                    <include>log4j.properties</include>
                </includes>
            </resource>
        </resources>
    </build>

</project>
```

**Comment by pwhitey86** [comment] 2016-09-28 21:10
This is the nn configuration:

```
ComputationGraphConfiguration conf = new NeuralNetConfiguration.Builder()
        .seed(12345)
        .iterations(1)
        .regularization(true).l2(knobs.getRegularization())
        .learningRate(knobs.getLearningRate())
        .weightInit(WeightInit.XAVIER)
        .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
        .graphBuilder()
        .addInputs("input")
        .addLayer("conv1",
            new ConvolutionLayer.Builder()
                .nIn(knobs.getNumChannels())
                .stride(1, 1)
                .kernelSize(knobs.getConvFilterSize(),1)
                .nOut(knobs.getConvNumFilters())
                .activation("relu")
                .updater(updater)
                .build(),
            new FeedForwardToCnnPreProcessor(knobs.getKnobsSampling().getLengthWindow(), knobs.getVectorSize(), knobs.getNumChannels()),
            "input")
        .addLayer("conv2",
            new ConvolutionLayer.Builder()
                .nIn(knobs.getConvNumFilters())
                .stride(1, 1)
                .kernelSize(knobs.getConvFilterSize(),1)
                .nOut(knobs.getConvNumFilters())
                .activation("relu")
                .updater(updater)
                .build(),
            "conv1")
        .addLayer("conv3",
            new ConvolutionLayer.Builder()
                .nIn(knobs.getConvNumFilters())
                .stride(1, 1)
                .kernelSize(knobs.getConvFilterSize(),1)
                .nOut(knobs.getConvNumFilters())
                .activation("relu")
                .updater(updater)
                .build(),
            "conv2")
        .addLayer("lstm1",
            new GravesLSTM.Builder()
                .nIn(knobs.getVectorSize() * knobs.getConvNumFilters())
                .nOut(knobs.getNumNodes())
                .activation("tanh")
                .build(),
            new HeightToTimePreProcessor(knobs.getFromShape(), knobs.getToShape()),
            "conv3")
        .addLayer("lstm2",
            new GravesLSTM.Builder()
                .nIn(knobs.getNumNodes())
                .nOut(knobs.getNumNodes())
                .activation("tanh")
                .build(),
            "lstm1")
        .addLayer("output",
            new RnnOutputLayer.Builder()
                .activation("softmax")
                .lossFunction(LossFunctions.LossFunction.MCXENT)
                .nIn(knobs.getNumNodes())
                .nOut(knobs.getNumLabels())
                .build(),
            "lstm2")
        .setOutputs("output")
        .backprop(true)
        .pretrain(false)
        .build();
```

**Comment by pwhitey86** [comment] 2016-09-28 21:23
All of stderr: https://gist.github.com/pwhitey86/8ffab9a0adbae30ace3a7363dbbaad48

All of log: https://gist.github.com/pwhitey86/82edf7cc0a1057239987fd150ff4d7de

**Comment by saudet** [comment] 2016-09-29 00:35
Sounds a lot like the errors that we're getting with out CI server on AWS

**Comment by raver119** [comment] 2016-09-29 07:20
can you post output with debug enabled? Also, what about run with float as dataType?

**Comment by raver119** [comment] 2016-09-29 07:37
@saudet nope, it's not. on CI that's issue from mixed dataTypes in single JVM session. definitely not the case here :(

@pwhitey86 got your messages in chat, so that's already with debug enabled, thanks.

**Comment by pwhitey86** [comment] 2016-09-29 14:04
@raver119 same error occurs when comment out half usage: `//DataTypeUtil.setDTypeForContext(DataBuffer.Type.HALF);`

**Comment by raver119** [comment] 2016-09-29 14:12
Awesome. Can i have input image dimensions/channels & num of output labels.

Actually it would be nice to get full knobs dump, i want to reproduce this thing at my working pc.

**Comment by pwhitey86** [comment] 2016-09-29 14:24
```
train.numLabels=200

train.knobsSampling.downSampleStep=4
train.knobsSampling.lengthWindow=128
train.knobsSampling.slideStep=4

train.knobs.batchSize=50
train.knobs.numNodes=32
train.knobs.learningRate=40e-3
train.knobs.regularization=1e-4
train.knobs.convFilterSize=32
train.knobs.convNumFilters=64
```

**Comment by raver119** [comment] 2016-09-29 14:25
What's your input then?

**Comment by raver119** [comment] 2016-09-29 14:26
Can you provide me with some self-containing DataSetIterator that generates datasets that look like yours, in terms of dimensionality?

**Comment by pwhitey86** [comment] 2016-09-29 14:28
Currently, the DataSetIntegrator uses other custom classes. Let me try to get one that is standalone.

**Comment by raver119** [comment] 2016-09-29 14:30
It could be just random data within those datasets, it should just look like yours, since we don't care about learning right now :)

**Comment by pwhitey86** [comment] 2016-09-29 14:58
Here is a DataSetIterator with a next function that gives data in the shape to run with the model

https://gist.github.com/pwhitey86/b6c63fe61dd6cafbfbddf2844afd809d

you'll also need

- "fromShape":[-1,64,35,4], "toShape":[-1,256,35]
- [HeightToTimePreprocessor](https://gist.github.com/pwhitey86/e1d9544daa7c73c89d7bac35e7d93090)

**Comment by raver119** [comment] 2016-09-30 22:15
Issue is fixed, but will be merged to master a bit later, probably tomorrow.

Thanks for highlighting this issue.

**Closed by raver119** 2016-09-30 22:15 UTC
Labels: bug

**Comment by pwhitey86** [comment] 2016-10-01 00:30
Thanks!
